"""empty message

Revision ID: 427c6b9a77e6
Revises: 
Create Date: 2024-12-20 16:40:44.472761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '427c6b9a77e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = reflection.Inspector.from_engine(bind)
    columns = [col['name'] for col in insp.get_columns('registered_users')]

    # FIX: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'push_enabled'")
    if 'push_enabled' not in columns:
        with op.batch_alter_table('registered_users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('push_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_column('push_enabled')

    # ### end Alembic commands ###
