"""3.1.0 - Add push_notifications_enabled boolean column for managing Push Notifications enable state.

Revision ID: 96ea605859a3
Revises: 
Create Date: 2024-12-20 02:47:10.299423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ea605859a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_users', schema=None) as batch_op:
        batch_op.drop_column('push_notifications_enabled')

    # ### end Alembic commands ###
