"""3.2.0 - Added Captcha Configuration Fields

Revision ID: ea57a5415350
Revises: 427c6b9a77e6
Create Date: 2025-06-28 01:09:25.933985

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = 'ea57a5415350'
down_revision = '427c6b9a77e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = reflection.Inspector.from_engine(bind)
    columns = [col['name'] for col in insp.get_columns('app_settings')]

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        if 'captcha_enabled' not in columns:
            batch_op.add_column(sa.Column('captcha_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True))

        if 'captcha_provider' not in columns:
            batch_op.add_column(sa.Column('captcha_provider', sa.String(length=32), nullable=True))

        if 'captcha_site_key' not in columns:
            batch_op.add_column(sa.Column('captcha_site_key', sa.String(length=128), nullable=True))

        if 'captcha_secret_key' not in columns:
            batch_op.add_column(sa.Column('captcha_secret_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    columns = [col['name'] for col in inspector.get_columns('app_settings')]

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        if 'captcha_secret_key' in columns:
            batch_op.drop_column('captcha_secret_key')

        if 'captcha_provider' in columns:
            batch_op.drop_column('captcha_provider')

        if 'captcha_site_key' in columns:
            batch_op.drop_column('captcha_site_key')

        if 'captcha_enabled' in columns:
            batch_op.drop_column('captcha_enabled')

    # ### end Alembic commands ###
