#!/bin/sh

GUNICORN_WORKERS="${GUNICORN_WORKERS:-1}"
GUNICORN_THREADS="${GUNICORN_THREADS:-4}"
GUNICORN_TIMEOUT="${GUNICORN_TIMEOUT:-60}"

gunicorn -w "$GUNICORN_WORKERS" --threads "$GUNICORN_THREADS" -t "$GUNICORN_TIMEOUT" -b 0.0.0.0:3030 wsgi:asklvkaszus_backend
